# Generated by Django 5.0.4 on 2024-06-28 08:40

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_models = apps.get_model('main_app', 'SmartPhone')

    for smartphone in smartphone_models.objects.all():
        smartphone.price = MULTIPLIER * len(smartphone.brand)
        smartphone.save()


def set_category(apps, schema_editor):
    smartphone_models = apps.get_model('main_app', 'SmartPhone')

    for smartphone in smartphone_models.objects.all():
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'
        smartphone.save()


def set_all_columns(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_changes(apps, schema_editor):
    smartphone_models = apps.get_model('main_app', 'SmartPhone')

    for smartphone in smartphone_models.objects.all():
        smartphone.category = smartphone_models._meta.get_field('category').default
        smartphone.price = smartphone_models._meta.get_field('price').default
        smartphone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_all_columns, reverse_changes)
    ]
